### ISSUE TITLE
conda env update --file environment.yml

### ISSUE THREAD

**Issue by mimi1981** [jiwidi/time-series-forecasting-with-python#5]
Great repo with so much useful info. I have tried to install you environment.yml environment without success (see below for error). 

(timeseries) Michels-MBP:time-series-forecasting-with-python micheltsamados$ conda env update --file environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - m2-bash==4.3.042=5
  - winpty==0.4.3=4
  - m2-bash-completion==2.3=2
  - m2-sed==4.2.2=3
  - m2w64-make==4.1.2351.a80a8
...

**Comment by jiwidi** [comment]
Mm, is been a long time since I installed from the conda env file. Could you try going for  `python -m pip install -r requirements.txt` for now (this will call your conda python interpreter pip installer and install al requirements) and I'll check into your error with more detail?

**Comment by mimi1981** [comment]
Thank you Jaime 
Really impressive collection of forecasting methods. Most are working for me but am still having some issues with xgboost, lightbbm and shap 

# import xgboost as xgb
# import lightgbm as lgb
import gluonts
from math import sqrt

# import shap

Thanks a lot 
Michel

**Comment by jiwidi** [comment]
Hi! I know is been a long time but I fixed the requeriments file to work with python 3.7

Follow instructions at https://github.com/jiwidi/time-series-forecasting-with-python/blob/master/docs/setup.md.

I'll close the issue for now but feel free to open it again if problem persists.
