### ISSUE TITLE
VMD

### ISSUE THREAD

**Issue by lightofhop** [jiwidi/time-series-forecasting-with-python#7]
Hi there, 

I was wondering whether you considered doing (Variational Mode Decomposition) VMD + LSTM model?

Thanks,
S

**Comment by jiwidi** [comment]
Hi!

No I haven't, in fact I didn't even know that model existed. Do you have some useful links to learn about it?

**Comment by lightofhop** [comment]
Hi,

Please check your email. I sent you some papers. Thanks.
